name: unit-tests
on:
  push:
  pull_request:
  schedule:
  - cron: 0 4 * * MON,FRI
jobs:
  OS:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - docker.io/debian:unstable
          - docker.io/ubuntu:devel
          - docker.io/ubuntu:rolling
          - docker.io/ubuntu:latest
          - registry.fedoraproject.org/fedora:latest
          - registry.fedoraproject.org/fedora:rawhide

    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run unit tests
        run: |
          dpkg -s podman docker || true
          cat /etc/apt/sources.list
          cat /etc/apt/sources.list.d/*
          tests/run ${{ matrix.scenario }}
